# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'ThoughtUser' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ThoughtUser
 pod 'OHHTTPStubs'
 pod 'OHHTTPStubs/Swift'

  target 'ThoughtUserTests' do
    inherit! :search_paths
    # Pods for testing
pod 'OHHTTPStubs'
pod 'OHHTTPStubs/Swift'
  end

  target 'ThoughtUserUITests' do
    inherit! :search_paths
    # Pods for testing
pod 'OHHTTPStubs'
pod 'OHHTTPStubs/Swift'
  end

end
